root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/server"
  cmd = "go build -o ./tmp/server ./main.go"
  args_bin = ["server", "public"]
  delay = 500
  exclude_dir = ["tmp", "gen", "scripts"]
  exclude_regex = ["_test\\.go"]
  include_ext = ["go", "yaml", "yml"]
  kill_delay = "2s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
