// CODE GENERATED BY tools/gen-route-info - DO NOT EDIT.
package reflectionmux

import (
	"reflect"

	rawdocdel "github.com/yunerou/niarb/core/domain/example/delivery"
)

var CommentExtractor = map[reflect.Type]map[string]string{
	reflect.TypeFor[rawdocdel.ExampleReqBody](): {
		"Field1": "Documentation for Field1: this is field1",
		"Field2": "Documentation for Field2: this is field2",
	},
	reflect.TypeFor[rawdocdel.ExampleReqParam](): {
		"Param1": "Documentation for Param1: this is param1",
		"Param3": "Documentation for Param2: this is param2",
	},
	reflect.TypeFor[rawdocdel.ExampleRespBody](): {
		"Message": "Documentation for Message: this is result",
	},
}
