// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package aerror

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrOrigin-1]
	_ = x[start400-10]
	_ = x[ErrInvalidInput-11]
	_ = x[ErrManyValidation-12]
	_ = x[ErrValidateRequired-13]
	_ = x[ErrValidateLen-14]
	_ = x[ErrValidateMin-15]
	_ = x[ErrValidateMax-16]
	_ = x[ErrValidateEq-17]
	_ = x[ErrValidateNe-18]
	_ = x[ErrValidateLt-19]
	_ = x[ErrValidateLte-20]
	_ = x[ErrValidateGt-21]
	_ = x[ErrValidateGte-22]
	_ = x[ErrValidateOneOf-23]
	_ = x[ErrValidateIndividualNumber-24]
	_ = x[ErrValidateImageBase64-25]
	_ = x[ErrValidatePassword-26]
	_ = x[ErrValidateUsername-27]
	_ = x[ErrValidateEmail-28]
	_ = x[ErrValidatePhone-29]
	_ = x[ErrValidateUUID-30]
	_ = x[end400-31]
	_ = x[start401-2000]
	_ = x[SessionExceededMaxAge-2001]
	_ = x[LogicErrSessionExpired-2002]
	_ = x[LogicErrUserNeedVerified-2003]
	_ = x[InvitationTokenInvalid-2004]
	_ = x[ConfirmationTokenInvalid-2005]
	_ = x[ResetPasswordTokenInvalid-2006]
	_ = x[RefreshTokenInvalid-2007]
	_ = x[LogicErrMissingAuthHeader-2008]
	_ = x[LogicErrAccessTokenVerifyFail-2009]
	_ = x[LogicErrSessionHasBeenRevoked-2010]
	_ = x[LogicErrWrongPassword-2011]
	_ = x[LogicErrAlreadyExistedPassword-2012]
	_ = x[LogicErrEmailOrPasswordIncorrect-2013]
	_ = x[ErrAccessTokenFormat-2014]
	_ = x[ErrConfirmationTokenFormat-2015]
	_ = x[ErrInvitationTokenFormat-2016]
	_ = x[ErrSignupConfirmTokenInvalid-2017]
	_ = x[ErrEmailUserAlreadyExists-2018]
	_ = x[end401-2019]
	_ = x[start403-4000]
	_ = x[LogicErrRefreshTokenIsExpired-4001]
	_ = x[LogicErrSessionHasBeenRevokedOrExpired-4002]
	_ = x[LogicErrSessionIsNotExisted-4003]
	_ = x[LogicErrInvalidRefreshToken-4004]
	_ = x[LogicErrInvalidToken-4005]
	_ = x[LogicRefreshTokenMustUseOnlyOnce-4006]
	_ = x[RateLimitExceeded-4007]
	_ = x[InvalidInputSchema-4008]
	_ = x[end403-4009]
	_ = x[start404-3000]
	_ = x[RecordNotFound-3001]
	_ = x[ErrDdbDuplicatedItem-3002]
	_ = x[end404-3003]
	_ = x[start500-6000]
	_ = x[ErrEncoder-6001]
	_ = x[ErrDecoder-6002]
	_ = x[ErrUnmarshal-6003]
	_ = x[ErrMarshal-6004]
	_ = x[ErrUnexpectedInput-6005]
	_ = x[ErrUnexpectedConfig-6006]
	_ = x[ErrUnexpectedTemplate-6007]
	_ = x[ErrUnexpectedSES-6008]
	_ = x[ErrUnexpectedRedis-6009]
	_ = x[ErrUnexpectedDatabase-6010]
	_ = x[ErrUnexpectedDynamoDB-6011]
	_ = x[ErrUnexpectedBussiness-6012]
	_ = x[ErrUnexpectedNetwork-6013]
	_ = x[ErrUnexpectedSyscall-6014]
	_ = x[ErrUnexpectedCodeLogic-6015]
	_ = x[ErrUnexpectedShouldUnreachable-6016]
	_ = x[ErrUnexpectedWithMsg-6017]
	_ = x[LogicErrDuplicateRecord-6018]
	_ = x[LogicErrOauth2ClientSecretNotMatch-6019]
	_ = x[LogicErrOauth2PkceCodeVerifierNotMatch-6020]
	_ = x[ErrUnexpectedPubsub-6021]
	_ = x[ErrServerIsShuttingDown-6022]
	_ = x[end500-6023]
	_ = x[start500NoTrace-8000]
	_ = x[ErrPermissionDenied-8001]
	_ = x[ActionNotAllowed-8002]
	_ = x[end500NoTrace-8003]
}

const (
	_ErrorCode_name_0 = "ErrOrigin"
	_ErrorCode_name_1 = "start400ErrInvalidInputErrManyValidationErrValidateRequiredErrValidateLenErrValidateMinErrValidateMaxErrValidateEqErrValidateNeErrValidateLtErrValidateLteErrValidateGtErrValidateGteErrValidateOneOfErrValidateIndividualNumberErrValidateImageBase64ErrValidatePasswordErrValidateUsernameErrValidateEmailErrValidatePhoneErrValidateUUIDend400"
	_ErrorCode_name_2 = "start401SessionExceededMaxAgeLogicErrSessionExpiredLogicErrUserNeedVerifiedInvitationTokenInvalidConfirmationTokenInvalidResetPasswordTokenInvalidRefreshTokenInvalidLogicErrMissingAuthHeaderLogicErrAccessTokenVerifyFailLogicErrSessionHasBeenRevokedLogicErrWrongPasswordLogicErrAlreadyExistedPasswordLogicErrEmailOrPasswordIncorrectErrAccessTokenFormatErrConfirmationTokenFormatErrInvitationTokenFormatErrSignupConfirmTokenInvalidErrEmailUserAlreadyExistsend401"
	_ErrorCode_name_3 = "start404RecordNotFoundErrDdbDuplicatedItemend404"
	_ErrorCode_name_4 = "start403LogicErrRefreshTokenIsExpiredLogicErrSessionHasBeenRevokedOrExpiredLogicErrSessionIsNotExistedLogicErrInvalidRefreshTokenLogicErrInvalidTokenLogicRefreshTokenMustUseOnlyOnceRateLimitExceededInvalidInputSchemaend403"
	_ErrorCode_name_5 = "start500ErrEncoderErrDecoderErrUnmarshalErrMarshalErrUnexpectedInputErrUnexpectedConfigErrUnexpectedTemplateErrUnexpectedSESErrUnexpectedRedisErrUnexpectedDatabaseErrUnexpectedDynamoDBErrUnexpectedBussinessErrUnexpectedNetworkErrUnexpectedSyscallErrUnexpectedCodeLogicErrUnexpectedShouldUnreachableErrUnexpectedWithMsgLogicErrDuplicateRecordLogicErrOauth2ClientSecretNotMatchLogicErrOauth2PkceCodeVerifierNotMatchErrUnexpectedPubsubErrServerIsShuttingDownend500"
	_ErrorCode_name_6 = "start500NoTraceErrPermissionDeniedActionNotAllowedend500NoTrace"
)

var (
	_ErrorCode_index_1 = [...]uint16{0, 8, 23, 40, 59, 73, 87, 101, 114, 127, 140, 154, 167, 181, 197, 224, 246, 265, 284, 300, 316, 331, 337}
	_ErrorCode_index_2 = [...]uint16{0, 8, 29, 51, 75, 97, 121, 146, 165, 190, 219, 248, 269, 299, 331, 351, 377, 401, 429, 454, 460}
	_ErrorCode_index_3 = [...]uint8{0, 8, 22, 42, 48}
	_ErrorCode_index_4 = [...]uint8{0, 8, 37, 75, 102, 129, 149, 181, 198, 216, 222}
	_ErrorCode_index_5 = [...]uint16{0, 8, 18, 28, 40, 50, 68, 87, 108, 124, 142, 163, 184, 206, 226, 246, 268, 298, 318, 341, 375, 413, 432, 455, 461}
	_ErrorCode_index_6 = [...]uint8{0, 15, 34, 50, 63}
)

func (i ErrorCode) String() string {
	switch {
	case i == 1:
		return _ErrorCode_name_0
	case 10 <= i && i <= 31:
		i -= 10
		return _ErrorCode_name_1[_ErrorCode_index_1[i]:_ErrorCode_index_1[i+1]]
	case 2000 <= i && i <= 2019:
		i -= 2000
		return _ErrorCode_name_2[_ErrorCode_index_2[i]:_ErrorCode_index_2[i+1]]
	case 3000 <= i && i <= 3003:
		i -= 3000
		return _ErrorCode_name_3[_ErrorCode_index_3[i]:_ErrorCode_index_3[i+1]]
	case 4000 <= i && i <= 4009:
		i -= 4000
		return _ErrorCode_name_4[_ErrorCode_index_4[i]:_ErrorCode_index_4[i+1]]
	case 6000 <= i && i <= 6023:
		i -= 6000
		return _ErrorCode_name_5[_ErrorCode_index_5[i]:_ErrorCode_index_5[i+1]]
	case 8000 <= i && i <= 8003:
		i -= 8000
		return _ErrorCode_name_6[_ErrorCode_index_6[i]:_ErrorCode_index_6[i+1]]
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
