package main

import (
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
	"strings"
)

// writeGenerated renders the CommentExtractor source file with one
// entry per discovered struct type and formats it before writing.
func writeGenerated(outputPath string, docs []structDoc) error {
	aliases := assignImportAliases(docs)

	var b strings.Builder
	b.WriteString("// CODE GENERATED BY tools/gen-route-info - DO NOT EDIT.\n")
	b.WriteString("package reflectionmux\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"reflect\"\n")
	if len(aliases) > 0 {
		b.WriteString("\n")
		for _, imp := range sortedImports(aliases) {
			fmt.Fprintf(&b, "\t%s %s\n", imp.Alias, strconv.Quote(imp.Path))
		}
	}
	b.WriteString(")\n\n")
	b.WriteString("var CommentExtractor = map[reflect.Type]map[string]string{\n")
	for _, d := range docs {
		alias := aliases[d.PkgPath]
		fmt.Fprintf(&b, "\treflect.TypeFor[%s.%s](): {\n", alias, d.TypeName)
		for _, name := range sortedKeys(d.FieldDocs) {
			fmt.Fprintf(&b, "\t\t%s: %s,\n",
				strconv.Quote(name),
				strconv.Quote(d.FieldDocs[name]),
			)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		// Write the unformatted source so the failure is debuggable.
		_ = os.WriteFile(outputPath, []byte(b.String()), 0o644)
		return fmt.Errorf("format generated source: %w", err)
	}
	return os.WriteFile(outputPath, formatted, 0o644)
}

type importEntry struct {
	Alias string
	Path  string
}

// assignImportAliases gives every distinct import path a unique alias.
// The first occurrence keeps the natural package name; subsequent
// collisions get a numeric suffix.
func assignImportAliases(docs []structDoc) map[string]string {
	aliases := map[string]string{}
	used := map[string]bool{"reflect": true}
	for _, d := range docs {
		if _, ok := aliases[d.PkgPath]; ok {
			continue
		}
		base := sanitizeIdent(d.PkgName)
		alias := base
		for i := 2; used[alias]; i++ {
			alias = base + strconv.Itoa(i)
		}
		aliases[d.PkgPath] = alias
		used[alias] = true
	}
	return aliases
}

func sortedImports(aliases map[string]string) []importEntry {
	out := make([]importEntry, 0, len(aliases))
	for path, alias := range aliases {
		out = append(out, importEntry{Alias: alias, Path: path})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// sanitizeIdent strips characters that are not valid in a Go
// identifier from a package name (e.g. dashes in directory names).
func sanitizeIdent(s string) string {
	var b strings.Builder
	for i, r := range s {
		switch {
		case r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z'):
			b.WriteRune(r)
		case i > 0 && r >= '0' && r <= '9':
			b.WriteRune(r)
		}
	}
	if b.Len() == 0 {
		return "pkg"
	}
	return b.String()
}
