// Code generated by "stringer -type=aCtxKey"; DO NOT EDIT.

package actx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[privKey-2]
}

const _aCtxKey_name = "privKey"

var _aCtxKey_index = [...]uint8{0, 7}

func (i aCtxKey) String() string {
	idx := int(i) - 2
	if i < 2 || idx >= len(_aCtxKey_index)-1 {
		return "aCtxKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _aCtxKey_name[_aCtxKey_index[idx]:_aCtxKey_index[idx+1]]
}
